name: Build & Publish Electron Releases

on:
  push:
    branches: ['chore/CI-publish']
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # Mac (including M1)
  build_on_mac:
    if: github.event.base_ref == 'refs/heads/$BRANCH'
    runs-on: macos-latest
    steps:
      # Checkout this branch
      - uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}

      # Installing node.js
      - uses: actions/setup-node@master
        with:
          node-version: 16

      # Installing dependencies with higher timeout in case of slow network
      - name: Install dependencies
        run: |
          yarn run install:slow
          yarn

      # Installing concurrently because sometimes doesn't install as part of yarn on macos
      # - name: Install Concurrently
      #   run: yarn add concurrently

      # Build and publish electron
      - name: Build Electron
        env:
          ELECTRON: true
          PUBLISH_FOR_PULL_REQUEST: false
          ELECTRON_CACHE: $HOME/.cache/electron
          ELECTRON_BUILDER_CACHE: $HOME/.cache/electron-builder
          USE_HARD_LINKS: false
          YARN_GPG: no
          GITHUB_TOKEN: ${{ secrets.github_token }}
        run: yarn run publish:mac

      - name: List all files in the release directory
        run: ls ./release/build

  # Windows
  build_on_win:
    if: github.event.base_ref == 'refs/heads/$BRANCH'
    runs-on: windows-latest
    steps:
      # Checkout this branch
      - uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}

      # Installing node.js
      - uses: actions/setup-node@master
        with:
          node-version: 16

      # Installing dependencies with higher timeout in case of slow network
      - name: Install dependencies
        run: |
          yarn run install:slow
          yarn

      # Installing electron-builder because doesn't install as part of yarn on windows
      # - name: Install Electron builder
      #   run: yarn add electron-builder

      # Build and publish electron
      - name: Build Electron
        env:
          ELECTRON: true
          PUBLISH_FOR_PULL_REQUEST: false
          ELECTRON_CACHE: $HOME/.cache/electron
          ELECTRON_BUILDER_CACHE: $HOME/.cache/electron-builder
          USE_HARD_LINKS: false
          YARN_GPG: no
          GITHUB_TOKEN: ${{ secrets.github_token }}
        run: yarn run publish:windows

      - name: List all files in the release directory
        run: ls ./release/build

  # Linux
  build_on_linux:
    # if: github.event.base_ref == 'refs/heads/$BRANCH'
    runs-on: ubuntu-latest
    steps:
      # Checkout this branch
      - uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}

      # Installing node.js
      - uses: actions/setup-node@master
        with:
          node-version: 16

      # Installing dependencies with higher timeout in case of slow network
      - name: Install dependencies
        run: |
          yarn run install:slow
          yarn

      - name: Build
        run: yarn run build

      - name: List .
        run: ls .

      # - name: List ./dist
      #   run: ls ./dist

      - name: List ./release
        run: ls ./release

      - name: List ./release/build
        run: ls ./release/build

      - name: List ./release/app
        run: ls ./release/app

      # Build and publish electron
      # - name: Build Electron
      #   env:
      #     ELECTRON: true
      #     PUBLISH_FOR_PULL_REQUEST: false
      #     ELECTRON_CACHE: $HOME/.cache/electron
      #     ELECTRON_BUILDER_CACHE: $HOME/.cache/electron-builder
      #     USE_HARD_LINKS: false
      #     YARN_GPG: no
      #     GITHUB_TOKEN: ${{ secrets.github_token }}
      #   run: yarn run publish:linux

      # - name: List all files in the release directory
      #   run: ls ./release/build
